ALTER TABLE users ADD COLUMN IF NOT EXISTS precision integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS guess integer NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS wordle integer NOT NULL DEFAULT 0;
